CREATE TABLE stwl_game_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR2(128) NOT NULL,
  room_id VARCHAR2(64) NOT NULL,
  player_id VARCHAR2(128) NOT NULL,
  player_name VARCHAR2(256),
  event_type VARCHAR2(40) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  score NUMBER,
  x NUMBER,
  y NUMBER,
  z NUMBER,
  related_player_id VARCHAR2(128),
  related_item_id VARCHAR2(128),
  metadata_json CLOB CHECK (metadata_json IS JSON),
  CONSTRAINT stwl_game_events_type_ck CHECK (
    event_type IN (
      'game_started',
      'position_sample',
      'trash_collected',
      'marine_hit',
      'powerup_collected',
      'trail_crossed',
      'player_frozen',
      'game_over'
    )
  )
);

CREATE INDEX stwl_game_events_session_ix ON stwl_game_events (session_id, occurred_at);
CREATE INDEX stwl_game_events_player_ix ON stwl_game_events (player_id, occurred_at);
CREATE INDEX stwl_game_events_type_ix ON stwl_game_events (event_type, occurred_at);

CREATE SEQUENCE stwl_game_events_seq START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE stwl_player_sessions (
  player_id VARCHAR2(128) PRIMARY KEY,
  client_session_id VARCHAR2(128),
  gameplay_session_id VARCHAR2(128),
  room_id VARCHAR2(64),
  player_name VARCHAR2(256),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  sessions_json CLOB CHECK (sessions_json IS JSON)
);

CREATE INDEX stwl_player_sessions_room_ix ON stwl_player_sessions (room_id, updated_at);

COMMENT ON TABLE stwl_game_events IS
  'Save the Wildlife gameplay timeline. Each row is one player event used by Oracle Private Agent Factory and Select AI demos.';
COMMENT ON TABLE stwl_player_sessions IS
  'Canonical Save the Wildlife player display names and browser/game session history for multiplayer identity tracking.';
COMMENT ON COLUMN stwl_game_events.session_id IS
  'Stable match/session identifier emitted by the game client or server.';
COMMENT ON COLUMN stwl_game_events.event_type IS
  'Gameplay event name: game_started, position_sample, trash_collected, marine_hit, powerup_collected, trail_crossed, player_frozen, game_over.';
COMMENT ON COLUMN stwl_game_events.x IS
  'World X coordinate at event time. World origin is center of the map.';
COMMENT ON COLUMN stwl_game_events.y IS
  'World Y coordinate at event time.';
COMMENT ON COLUMN stwl_game_events.z IS
  'World Z coordinate at event time.';
COMMENT ON COLUMN stwl_game_events.metadata_json IS
  'Event-specific JSON metadata such as powerup type, freeze duration, trail segment, item position, and final session stats.';

CREATE OR REPLACE VIEW stwl_session_summary AS
SELECT
  session_id,
  room_id,
  player_id,
  MAX(player_name) AS player_name,
  MIN(occurred_at) AS started_at,
  MAX(occurred_at) AS ended_at,
  COALESCE(
    MAX(CASE
      WHEN event_type = 'game_over'
       AND COALESCE(JSON_VALUE(metadata_json, '$.score_source'), JSON_VALUE(metadata_json, '$.scoreSource')) = 'server_room_state'
      THEN score
    END) KEEP (DENSE_RANK LAST ORDER BY CASE
      WHEN event_type = 'game_over'
       AND COALESCE(JSON_VALUE(metadata_json, '$.score_source'), JSON_VALUE(metadata_json, '$.scoreSource')) = 'server_room_state'
      THEN occurred_at
    END NULLS FIRST),
    MAX(CASE WHEN event_type = 'game_over' AND score <> 0 THEN score END)
      KEEP (DENSE_RANK LAST ORDER BY CASE WHEN event_type = 'game_over' AND score <> 0 THEN occurred_at END NULLS FIRST),
    MAX(CASE WHEN event_type <> 'game_over' AND score IS NOT NULL THEN score END)
      KEEP (DENSE_RANK LAST ORDER BY CASE WHEN event_type <> 'game_over' AND score IS NOT NULL THEN occurred_at END NULLS FIRST),
    MAX(CASE WHEN event_type = 'game_over' THEN score END)
      KEEP (DENSE_RANK LAST ORDER BY CASE WHEN event_type = 'game_over' AND score IS NOT NULL THEN occurred_at END NULLS FIRST),
    MAX(score) KEEP (DENSE_RANK LAST ORDER BY occurred_at)
  ) AS final_score,
  SUM(CASE WHEN event_type = 'trash_collected' THEN 1 ELSE 0 END) AS trash_collected,
  SUM(CASE WHEN event_type = 'marine_hit' THEN 1 ELSE 0 END) AS marine_hits,
  SUM(CASE WHEN event_type = 'powerup_collected' THEN 1 ELSE 0 END) AS powerups_collected,
  SUM(CASE WHEN event_type = 'trail_crossed' THEN 1 ELSE 0 END) AS trail_crosses,
  SUM(CASE WHEN event_type = 'player_frozen' THEN 1 ELSE 0 END) AS freezes
FROM stwl_game_events
GROUP BY session_id, room_id, player_id;

COMMENT ON TABLE stwl_session_summary IS
  'Derived per-session gameplay summary for deterministic commentary prompts and Select AI demos.';

CREATE OR REPLACE TRIGGER stwl_game_events_score_guard
BEFORE INSERT ON stwl_game_events
FOR EACH ROW
WHEN (NEW.event_type = 'game_over')
DECLARE
  v_latest_score stwl_game_events.score%TYPE;
  v_score_source VARCHAR2(128);
BEGIN
  BEGIN
    SELECT COALESCE(
             JSON_VALUE(:NEW.metadata_json, '$.score_source'),
             JSON_VALUE(:NEW.metadata_json, '$.scoreSource')
           )
      INTO v_score_source
      FROM dual;
  EXCEPTION
    WHEN OTHERS THEN
      v_score_source := NULL;
  END;

  IF NVL(v_score_source, 'client') <> 'server_room_state'
     AND (:NEW.score IS NULL OR :NEW.score = 0) THEN
    BEGIN
      SELECT score
        INTO v_latest_score
        FROM (
          SELECT score
            FROM stwl_game_events
           WHERE session_id = :NEW.session_id
             AND player_id = :NEW.player_id
             AND event_type <> 'game_over'
             AND score IS NOT NULL
             AND occurred_at <= :NEW.occurred_at
           ORDER BY occurred_at DESC, id DESC
        )
       WHERE ROWNUM = 1;

      IF v_latest_score IS NOT NULL THEN
        :NEW.score := v_latest_score;
      END IF;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        NULL;
    END;
  END IF;
END;
/
