apiVersion: v1
kind: Service
metadata:
  labels:
    app: private-agent-factory
  name: private-agent-factory
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: private-agent-factory
