apiVersion: v1
kind: Service
metadata:
  name: replay
  labels:
    app: replay
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: replay
  ports:
    - name: http
      port: 8082
      targetPort: 8082
