apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replay
  name: replay
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: replay
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: replay
    spec:
      initContainers:
      - name: unzip
        image: busybox
        command: ["unzip", "/walletzip/wallet.zip", "-d", "/wallet"]
        volumeMounts:
          - name: wallet-config
            mountPath: /walletzip
          - name: wallet-volume
            mountPath: /wallet
      containers:
        - image: replay
          imagePullPolicy: "Always"
          name: replay
          ports:
            - containerPort: 8082
          env:
          - name: SPRING_CONFIG_ADDITIONAL_LOCATION
            value: "file:/config/"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: wallet-volume
              mountPath: /wallet
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
      - name: config-volume
        configMap:
          name: replay-properties
      - name: wallet-config
        configMap:
          name: replay-wallet-zip
      - name: wallet-volume
        emptyDir:
          sizeLimit: 50Mi
      imagePullSecrets:
        - name: ocir-secret
