apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
spec:
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: ws-server
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1536"
            - name: PHYS_TURN_SPEED
              value: "0.78"
            - name: COLLISION_VALIDATE_RADIUS
              value: "5.2"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-agent-factory
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: private-agent-factory
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              cpu: 2000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score
spec:
  template:
    spec:
      containers:
        - name: score
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1500m
              memory: 2Gi
